# Generated by Django 3.1.5 on 2021-02-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='spending',
            new_name='spend',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='weekly_expenses',
            new_name='weekly_expen',
        ),
    ]
