# Generated by Django 3.1.5 on 2021-02-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='spend',
            new_name='spending',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='weekly_expen',
            new_name='weekly_expenses',
        ),
    ]
